FROM node:14.18.1-alpine

#RUN yarn config set unsafe-perm true

RUN yarn global add vite sass

USER root
WORKDIR /home/node/app
RUN chown -R node:node /home/node/app
COPY --chown=node:node ./package.json .

USER node
RUN yarn

COPY --chown=node:node . .
